server:
  port: 8888
spring:
  application:
    name: gateway-service
  security:
    user:
      name: admin
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8001/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
      - id: blockchain-ore  #ore微服务(随便取的)
        uri: lb://blockchain-ore-server
        predicates:
        - Path=/ore/user/**
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1  # 令牌桶的容积
            redis-rate-limiter.burstCapacity: 3  # 流速 每秒
            key-resolver: "#{@userKeyResolver}" #SPEL表达式去的对应的bean
        - StripPrefix=1

      - id: blockchain-eth  #eth微服务(随便取的)
        uri: lb://blockchain-eth-server
        predicates:
        - Path=/eth/user/**
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1  # 令牌桶的容积
            redis-rate-limiter.burstCapacity: 3  # 流速 每秒
            key-resolver: "#{@remoteAddrKeyResolver}" #SPEL表达式去的对应的bean
        - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

#feign:
  #hystrix:
    #enabled: true