server:
  port: 8003
spring:
  application:
    name: dapp-zuul-gateway
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8001/eureka/
  instance:
    prefer-ip-address: true

security:
  basic:
    enabled: false

zuul:
  routes:
    api-a:
      path: /blockchain-eth-server/**
      sensitiveHeaders: "*"
      serviceId: blockchain-eth-server
    api-b:
       path: /blockchain-ore-server/**
       sensitiveHeaders: "*"
       serviceId: blockchain-ore-server
